In [2]:
#to ignore compat.v1 for tensorflow
import pandas as pd
import numpy as np
import tensorflow as tf
seed = 1234
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
dataset = pd.read_csv('Iris_Dataset.csv') #dat format is also available
dataset = pd.get_dummies(dataset, columns=['Species'])
values = list(dataset.columns.values)

In [4]:
values

['Id',
 'SepalLengthCm',
 'SepalWidthCm',
 'PetalLengthCm',
 'PetalWidthCm',
 'Species_Iris-setosa',
 'Species_Iris-versicolor',
 'Species_Iris-virginica']

In [8]:
y = dataset[values[-3:]]
y = np.array(y, dtype='float32')

In [11]:
X = dataset[values[1:-3]]
X = np.array(X, dtype='float32')

In [12]:
indices = np.random.choice(len(X), len(X), replace=False)

In [13]:
indices

array([ 91,  63, 103,   6,  59,  29,  27,  35,  99, 122,  82,  42, 117,
        61,  43,  79, 100,  25, 108,  94,  74,  54,  51,  73, 109,  48,
       123,  92, 102,  11,  98, 126,  40, 133,  77,  24,   8,  20,  22,
        93,  36,  68,  32, 141, 125,   9, 114, 145, 135, 140,   1, 147,
       105,  97,  57,  64,  66,  52,  58,  17,  39, 130, 113, 110,  21,
        33,   0, 146,  62, 134, 144,  55,   4, 111,  10, 131,  15,  78,
        88,   5,  67,   7, 148, 132, 138,  85,  18,  49, 149,  83,  90,
        44,  86, 104,  70,  56,  72,  41,  16,  45,  84,  89,  31, 101,
        95, 137, 142,  96,  13,  87, 119,  28,  46, 139, 106,  60,  71,
       121,  14,  81, 107, 115, 129,  65,  12,  19,   2,   3, 136,  75,
       128,  34,  37,  76,  50, 127,  80,  69, 112, 120, 118,  26, 124,
        30,  23, 143, 116,  53,  38,  47])

In [16]:
X_values = X[indices]
y_values = y[indices]

In [17]:
X_values

array([[6.1, 3. , 4.6, 1.4],
       [6.1, 2.9, 4.7, 1.4],
       [6.3, 2.9, 5.6, 1.8],
       [4.6, 3.4, 1.4, 0.3],
       [5.2, 2.7, 3.9, 1.4],
       [4.7, 3.2, 1.6, 0.2],
       [5.2, 3.5, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 3.9, 1.2],
       [4.4, 3.2, 1.3, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [5.9, 3. , 4.2, 1.5],
       [5. , 3.5, 1.6, 0.6],
       [5.7, 2.6, 3.5, 1. ],
       [6.3, 3.3, 6. , 2.5],
       [5. , 3. , 1.6, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.7, 4.2, 1.3],
       [6.4, 2.9, 4.3, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [7.2, 3.6, 6.1, 2.5],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 2.7, 4.9, 1.8],
       [5.8, 2.6, 4. , 1.2],
       [7.1, 3. , 5.9, 2.1],
       [4.8, 3.4, 1.6, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [6.2, 2.8, 4.8, 1.8],
       [5. , 3.5, 1.3, 0.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.7, 3

In [18]:
y_values

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0

In [19]:
test_size = 10

In [20]:
X_test = X_values[-test_size:]
X_train = X_values[:-test_size]
y_test = y_values[-test_size:]
y_train = y_values[:-test_size]

In [21]:
X_test

array([[7.7, 2.6, 6.9, 2.3],
       [5. , 3.4, 1.6, 0.4],
       [6.7, 3.3, 5.7, 2.1],
       [4.8, 3.1, 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.8, 3.2, 5.9, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [5.5, 2.3, 4. , 1.3],
       [4.4, 3. , 1.3, 0.2],
       [4.6, 3.2, 1.4, 0.2]], dtype=float32)

In [23]:
y_test

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [24]:
sess = tf.Session()
interval = 100
epoch = 850

In [25]:
X_data = tf.placeholder(shape=[None, 4], dtype=tf.float32)
y_target = tf.placeholder(shape=[None, 3], dtype=tf.float32)

In [27]:
hidden_layer_nodes = 8
w1 = tf.Variable(tf.random_normal(shape=[4,hidden_layer_nodes])) 
b1 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes]))   
w2 = tf.Variable(tf.random_normal(shape=[hidden_layer_nodes,3])) 
b2 = tf.Variable(tf.random_normal(shape=[3]))

In [29]:
#Functions
hidden_output = tf.nn.relu(tf.add(tf.matmul(X_data, w1), b1))
final_output = tf.nn.softmax(tf.add(tf.matmul(hidden_output, w2), b2))
loss = tf.reduce_mean(-tf.reduce_sum(y_target * tf.log(final_output), axis=0))

In [31]:
# Minimizing loss
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

In [32]:
init = tf.global_variables_initializer()
sess.run(init)


print('Training the model...')
for i in range(1, (epoch + 1)):
    sess.run(optimizer, feed_dict={X_data: X_train, y_target: y_train})
    if i % interval == 0:
        print('Epoch', i, '|', 'Loss:', sess.run(loss, feed_dict={X_data: X_train, y_target: y_train}))

# THE TEST
print()
for i in range(len(X_test)):
    print('Actual:', y_test[i], 'Predicted:', np.rint(sess.run(final_output, feed_dict={X_data: [X_test[i]]})))

Training the model...
Epoch 100 | Loss: 13.553829
Epoch 200 | Loss: 7.478199
Epoch 300 | Loss: 5.577091
Epoch 400 | Loss: 4.6667247
Epoch 500 | Loss: 4.0857043
Epoch 600 | Loss: 3.7464879
Epoch 700 | Loss: 3.5182965
Epoch 800 | Loss: 3.3516538

Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 1. 0.] Predicted: [[0. 1. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]


In [33]:
print('Training the model...')
for i in range(1, (epoch + 1)):
    sess.run(optimizer, feed_dict={X_data: X_train, y_target: y_train})
    if i % interval == 0:
        print('Epoch', i, '|', 'Loss:', sess.run(loss, feed_dict={X_data: X_train, y_target: y_train}))

# THE TEST
print()
for i in range(len(X_test)):
    print('Actual:', y_test[i], 'Predicted:', np.rint(sess.run(final_output, feed_dict={X_data: [X_test[i]]})))

Training the model...
Epoch 100 | Loss: 3.170903
Epoch 200 | Loss: 3.0797842
Epoch 300 | Loss: 3.0047257
Epoch 400 | Loss: 2.9413166
Epoch 500 | Loss: 2.8868277
Epoch 600 | Loss: 2.8393447
Epoch 700 | Loss: 2.7974303
Epoch 800 | Loss: 2.7599366

Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 1. 0.] Predicted: [[0. 1. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]


In [34]:
init = tf.global_variables_initializer()
sess.run(init)


print('Training the model...')
for i in range(1, (epoch + 1)):
    sess.run(optimizer, feed_dict={X_data: X_train, y_target: y_train})
    if i % interval == 0:
        print('Epoch', i, '|', 'Loss:', sess.run(loss, feed_dict={X_data: X_train, y_target: y_train}))

# THE TEST
print()
for i in range(len(X_test)):
    print('Actual:', y_test[i], 'Predicted:', np.rint(sess.run(final_output, feed_dict={X_data: [X_test[i]]})))

Training the model...
Epoch 100 | Loss: 8.625345
Epoch 200 | Loss: 6.1616936
Epoch 300 | Loss: 5.155749
Epoch 400 | Loss: 4.5994306
Epoch 500 | Loss: 4.2433395
Epoch 600 | Loss: 3.9949977
Epoch 700 | Loss: 3.810321
Epoch 800 | Loss: 3.666869

Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 1. 0.] Predicted: [[0. 1. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]


In [35]:
init = tf.global_variables_initializer()
sess.run(init)


print('Training the model...')
for i in range(1, (epoch + 1)):
    sess.run(optimizer, feed_dict={X_data: X_train, y_target: y_train})
    if i % interval == 0:
        print('Epoch', i, '|', 'Loss:', sess.run(loss, feed_dict={X_data: X_train, y_target: y_train}))

# THE TEST
print()
for i in range(len(X_test)):
    print('Actual:', y_test[i], 'Predicted:', np.rint(sess.run(final_output, feed_dict={X_data: [X_test[i]]})))

Training the model...
Epoch 100 | Loss: 6.866379
Epoch 200 | Loss: 5.0728807
Epoch 300 | Loss: 4.484039
Epoch 400 | Loss: 4.179488
Epoch 500 | Loss: 3.9899273
Epoch 600 | Loss: 3.8587468
Epoch 700 | Loss: 3.7613432
Epoch 800 | Loss: 3.6852458

Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 0. 1.] Predicted: [[0. 0. 1.]]
Actual: [0. 1. 0.] Predicted: [[0. 1. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
Actual: [1. 0. 0.] Predicted: [[1. 0. 0.]]
